---
title: "Untitled"
author: "Jaehwan Lim"
date: "January 30, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}
library(tidyverse)
library(gt)
library(cowplot)
library(xtable)
library(reshape)

women_cases_raw <- read_csv("glynn_sen_daughters_by_case_1.csv") %>% select(-X1) 

judge_means_raw <- read_csv("glynn_sen_daughters_by_judge.csv") %>% select(-X1)

```

```{r}
## subsetting the dataset

women_cases <- women_cases_raw %>%
  filter(femplaintiff == 1) %>%  
  filter(area %in% c("employment", "Title IX", "pregnancy", "abortion", "reproductive rights")) 

women_cases$area <- factor(women_cases$area, levels = c("abortion","employment","pregnancy","reproductive rights","Title IX"))

judge_means <- judge_means_raw %>% 
  filter(girls != "NaN")

```

```{r}
by_childs <- judge_means %>% 
  mutate(republican = recode(republican, `0` = "Democrat", 
                             `1` = "Republican")) %>% 
  group_by(child) %>%
  count(republican) %>% 
  spread(republican, n) 

by_girls <- judge_means %>% 
  mutate(republican = recode(republican, `0` = "Democrat", 
                             `1` = "Republican")) %>% 
  group_by(girls) %>%
  count(republican) %>% 
  spread(republican, n) 

```

## Table 2
```{r}
# setup to avoid scientific number notation
options(scipen=999)

judge_all <- judge_means %>%
  summarize(mean_childs = mean(child), 
            mean_girls = mean(girls), 
            prop_zerochild = mean(child == 0), 
            child_1 = mean(child == 1), 
            child_2 = mean(child == 2), 
            child_3 = mean(child == 3), 
            child_4 = mean(child == 4), 
            child_5 = mean(child == 5),
            child_6 = mean(child >= 6), 
            prop_female = mean(woman == 1), 
            prop_republican = mean(republican == 1), 
            prop_white = mean(race == 1, na.rm = T), 
            mean_bornyear = mean(yearb, na.rm = T), 
            N = n())

judge_partisan <- judge_means %>% 
  mutate(republican = recode(republican, `0` = "Democrat", 
                             `1` = "Republican")) %>% 
  group_by(republican) %>%
  summarize(mean_childs = mean(child), 
            mean_girls = mean(girls), 
            prop_zerochild = mean(child == 0), 
            child_1 = mean(child == 1), 
            child_2 = mean(child == 2), 
            child_3 = mean(child == 3), 
            child_4 = mean(child == 4), 
            child_5 = mean(child == 5),
            child_6 = mean(child >= 6), 
            prop_female = mean(woman == 1), 
            prop_republican = mean(republican == 1),
            prop_white = mean(race == 1, na.rm = T), 
            mean_bornyear = mean(yearb, na.rm = T), 
            N = n())

judge_gender <- judge_means %>% 
  mutate(woman = recode(woman, `0` = "Men", 
                        `1` = "Women")) %>%
  summarize(mean_childs = mean(child), 
            mean_girls = mean(girls), 
            prop_zerochild = mean(child == 0), 
            child_1 = mean(child == 1), 
            child_2 = mean(child == 2), 
            child_3 = mean(child == 3), 
            child_4 = mean(child == 4), 
            child_5 = mean(child == 5),
            child_6 = mean(child >= 6), 
            prop_female = mean(woman == 1), 
            prop_republican = mean(republican == 1), 
            prop_white = mean(race == 1, na.rm = T), 
            mean_bornyear = mean(yearb, na.rm = T), 
            N = n())

# transpose the data frame

judge_all_trans <- judge_all %>% 
  rownames_to_column %>%
  gather(var, value, -rowname) %>% 
  spread(rowname, value)

judge_all_trans <- judge_all_trans[order(match(judge_all_trans$var, names(judge_all))),]

judge_partisan_trans <- judge_partisan %>% 
  rownames_to_column %>%
  gather(var, value, -rowname) %>% 
  spread(rowname, value)

judge_partisan_trans <- judge_partisan_trans[order(match(judge_partisan_trans$var, names(judge_partisan))),]

judge_gender_trans <- judge_gender %>% 
  rownames_to_column %>%
  gather(var, value, -rowname) %>% 
  spread(rowname, value)

judge_gender_trans <- judge_gender_trans[order(match(judge_gender_trans$var, names(judge_gender))),]

```
## figure 1: Distribution of the proportion of cases decided in a feminist direction out of all gender-related cases decide, 1996-2002

```{r}
# calculating the weights (the number of cases)
no_cases <- matrix(data = NA, nrow = nrow(judge_means_raw), ncol = 1)

for(i in 1:length(no_cases)){
	no_cases[i] <- nrow(women_cases[which(women_cases$name == judge_means_raw$name[i]),])
	}

judge_means <- cbind(judge_means_raw, no_cases)

## total number of cases we are working with

sum(judge_means$no_cases) 	# should be 2,674 reported in the paper

########################################################
## Calculating the Outcome Var
########################################################

no_liberalvote <- matrix(data = NA, nrow = nrow(judge_means), ncol = 1)
for(i in 1:length(no_liberalvote)){
	stuff <- women_cases[which(women_cases$name == judge_means$name[i]),]
	no_liberalvote[i] <- nrow(subset(stuff, vote == 2 | vote == 3))
	}

lib_vote_share <- no_liberalvote/no_cases

judge_means <- cbind(judge_means, no_liberalvote, lib_vote_share)
judge_means <- subset(judge_means, girls != "NaN")

########################################################
## Subsetting Data to Various Populations (for use later)
########################################################

## just women:
women_means <- subset(judge_means, woman == 1)

## just men:
men_means <- subset(judge_means, woman == 0)

## just republicans:
rep_means <- subset(judge_means, republican == 1)

## just democrats
dem_means <- subset(judge_means, republican == 0)



#######################################################
## Figure 1
########################################################

#pdf(file= "lib_votes.pdf", width = 5, height = 5, family = "Helvetica", pointsize = 10)
plot(density(judge_means$lib_vote_share), 
	xlim = c(-.4,1.4), ylim = c(0,2.5),
	ylab = "", xlab = "Proportion of Cases Decided in a Feminist Direction", 
	yaxt = "n", 
	bty = "n", 
	main = "",
	col = "black", lwd = 2)

ggplot(judge_means, aes(lib_vote_share)) + 
  geom_histogram() 

lines(density(rep_means$lib_vote_share), 
	col = "firebrick", lwd = 2, lty  = 2)

lines(density(dem_means$lib_vote_share), 
	col = "dodgerblue", lwd = 2, lty  = 3)

abline(v = .5, col = "grey50", lty = 2)
text(x = .5, y = 2.4, "Less Feminist", col = "grey50", pos = 2, cex = 0.9)
text(x = .5, y = 2.4, "More Feminist", col = "grey50", pos = 4, cex = 0.9)
text(x = .25, y = 1.7, "Republicans", pos = 2, cex = 0.9)
text(x = .7, y = 1, "Democrats", pos = 4, cex = 0.9)
text(x = .075, y = .6, "All", pos = 4, cex = 0.9)
#dev.off()

```
## Model

```{r}
## what is the merit of transforming into tibble?

judge_means <- as_tibble(judge_means)

glimpse(judge_means)
summary(judge_means)


my.out1 <- lm(lib_vote_share ~ as.factor(girls) + as.factor(child), 
	data = judge_means, weights = judge_means$no_cases)

summary(my.out1)

my.out2 <- lm(lib_vote_share ~ I(girls>0), 
	data = judge_means, weights = judge_means$no_cases)

summary(my.out2)

circuit <- lm(lib_vote_share ~ circuit.1, data = judge_means, weights = judge_means$no_cases)

## what else could be the reasonable way of checking the robustness?

my.out3 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3), 
	data = judge.means, weights = judge.means$no_cases)

my.out4 <- lm(lib_vote_share ~ I(girls>0) + as.factor(child) + republican + age + I(religion == 4) + woman + I(race == 2) + I(race ==3) + as.factor(circuit.1), 
	data = judge.means, weights = judge.means$no_cases)

```


